### ISSUE TITLE
Some clerical errors in the README.md file.

### ISSUE THREAD

**Issue by SwordJack** [ChemBioHTP/EnzyHTP#134]
There're some clerical errors found in the [Dependence](https://github.com/ChemBioHTP/EnzyHTP#dependence) section of the README file:

> ...
> install pandas `conda install pandas`
> install pandas `conda install mdtraj`
> install pandas `conda install -c conda-forge pymol-open-source`
> Install openbabel `conda install openbabel -c conda-forge`
> ...

Perhaps the text block would be better if it could be corrected to as follows.

> ...
> install pandas `conda install pandas`
> install MDTraj `conda install mdtraj`
> install Pymol `conda install -c conda-forge pymol-open-source`
> Install openbabel `conda install openbabel -c conda-forge`
> ...

Thanks!

**Comment by shaoqx** [comment]
addressed in 9deea0d28cba61bac8a8f9d88df52ab948d767d6
