### ISSUE TITLE
cpu_mem cannot parse strings with unit 'G'

### ISSUE THREAD

**Issue by KleinesMesser** [ChemBioHTP/EnzyHTP#59]
If res_setting is a string, cpu_mem has to be an integer or string with pure numbers like '3'. The current version cannot parse strings with trailing unit 'G'.

**Comment by KleinesMesser** [comment]
Currently, the unit of cpu_mem is MB, which is not intended.

**Comment by shaoqx** [comment]
This is fixed in #58
